version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: zenkaidb
    environment:
      POSTGRES_USER: zenkai_user
      POSTGRES_PASSWORD: zenkai_password
      POSTGRES_DB: zenkai_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 